Repository 3NCRY9T3R/H4CKT0B3RF3ST-2020, pull requests merged in 2020-10, with the labels that each got.

#38 Majority_Element.py
  Programs/Majority_Element.py
  Programs/Solution_code_chef_snakeeat.py
Labels: hacktoberfest-accepted

#55 Overview of OOPS in Python
  Programs/OOPS in Python.py
Labels: good first issue, hacktoberfest-accepted

#59 Create kthSmallestElement.cpp
  Programs/kthSmallestElement.cpp
Labels: hacktoberfest-accepted

#61 Create Sort_0s_1s.cpp
  Programs/Sort_0s_1s
Labels: hacktoberfest-accepted

#64 Create MergeKArrays.cpp
  Programs/MergeKArrays
Labels: hacktoberfest-accepted

#65 Create Anagrams.cpp
  Programs/Anagrams
Labels: hacktoberfest-accepted

#68 Create speeding_ticket.c
  Programs/speeding_ticket.c
Labels: hacktoberfest-accepted

#67 Stack implementation of array using cpp
  Programs/stack_array.cpp
Labels: hacktoberfest-accepted

#77 Programs/NQueens.java
  NQueens.java
Labels: hacktoberfest-accepted

#9 Create real_number_binary.cpp
  Programs/real_number_binary.cpp
Labels: hacktoberfest-accepted

#76 Create CurrencyConversion.java
  Programs/CurrencyConversion.java
Labels: hacktoberfest-accepted

#78 Create ParanthesisChecker.cpp
  Programs/ParanthesisChecker.cpp
Labels: hacktoberfest-accepted

#79 Polynomial_ll.c
  Polynoial_ll.c
Labels: hacktoberfest-accepted

#80 Create SieveOfEratosthenes.cpp
  Programs/SieveOfEratosthenes.cpp
Labels: hacktoberfest-accepted

#81 add FloydsTortoiseAndHare JAVA Program
  Programs/FloydsTortoiseAndHare.java
Labels: hacktoberfest-accepted

#89 Create SortingAlgorithms.py
  Programs/SortingAlgorithms.py
Labels: good first issue, hacktoberfest-accepted

#90 Create edit_distance.cpp
  Programs/edit_distance.cpp
Labels: hacktoberfest-accepted

#82 Create fibonacci.c
  Programs/fibonacci.c
Labels: hacktoberfest-accepted

#83 Create DiagonalDifference.java
  Programs/DiagonalDifference.java
Labels: hacktoberfest-accepted

#85 Create insertionSort.c
  Programs/insertionSort.c
Labels: hacktoberfest-accepted

#86 Create SelectionSort.c
  Programs/SelectionSort.c
Labels: hacktoberfest-accepted

#87 Create BubbleSort.c
  Programs/BubbleSort.c
Labels: hacktoberfest-accepted

#88 Greatest Common Divisor using Euclid's Algorithm in c
  Programs/GCD.c
Labels: hacktoberfest-accepted

#93 Hashing Concept
  Programs/open_addressing.cpp
Labels: hacktoberfest-accepted

#94 Print the pattern of right angle triangle in c
  rightangledprogram.c
Labels: hacktoberfest-accepted

#95 added "wave sorted array"
  Programs/wavearray.cpp
Labels: hacktoberfest-accepted

#96 Create Doreamon.py
  Programs/Doreamon.py
Labels: hacktoberfest-accepted

#97 Create car_fuelling.py
  Programs/car_fuelling.py
Labels: hacktoberfest-accepted

#107 Create RussianDoll_Envelopes.java
  Programs/RussianDoll_Envelopes.java
Labels: hacktoberfest-accepted

#108 Queue in C
  Programs/queue.c
Labels: hacktoberfest-accepted

#110 Create StackReversal.java
  Programs/StackReversal.java
Labels: hacktoberfest-accepted

#112 Added hamming code calculator
  Programs/hamming.py
Labels: hacktoberfest-accepted

#113 Create UglyNumbers.cpp
  Programs/UglyNumbers.cpp
Labels: hacktoberfest-accepted

#116 Create implementation_of_stack_without_using_array_and_pointers.c
  Programs/implementation_of_stack_without_using_array_and_pointers.c
Labels: hacktoberfest-accepted

#56 Create MinMaxSum.java
  Programs/MinMaxSum.java
Labels: hacktoberfest-accepted

#134 Add EqualSweetNess
  Programs/EqualSweetness.java
Labels: hacktoberfest-accepted

#133 Create Stock_Span.java
  programs/Stock_Span.java
Labels: hacktoberfest-accepted

#132 Create LCA_BST.java
  programs/LCA_BST.java
Labels: hacktoberfest-accepted

#140 Create Expression_evaluator.c
  Programs/Expression_evaluator.c
Labels: hacktoberfest-accepted

#139 Create Infix_to_postfix.c
  Programs/Infix_to_postfix.c
Labels: hacktoberfest-accepted

#122 Create GeometricSum.java
  Programs/GeometricSum.java
Labels: hacktoberfest-accepted

#123 SeparateDuplicates.java
  Programs/SeparateDuplicates.java
Labels: hacktoberfest-accepted

#99 Create Sum_of-Even_Numbers_till_N.java
  Programs/import java.util.Scanner; public class Solution {    public static void main(String[] args) {/* Your class should be named Solution.    * Read input as specified in the question.    * Print output as specified in the question.   */Sum_of-Even_Numbers_till_N.java
Labels: hacktoberfest-accepted

#148 Create Cryptarithmetic.java
  Programs/Cryptarithmetic.java
Labels: hacktoberfest-accepted

#147 Create Crossword.java
  Programs/Crossword.java
Labels: hacktoberfest-accepted

#146 Create Pattern_Matching.java
  Programs/Pattern_Matching.java
Labels: hacktoberfest-accepted

#145 Create Tug_of_War.java
  Programs/Tug_of_War.java
Labels: hacktoberfest-accepted

#144 Solving postfix expression using Stacks
  Programs/postfix-stack.cpp
Labels: hacktoberfest-accepted

#143 Create coinchange_numberofways.cpp
  Programs/coinchange_numberofways.cpp
Labels: hacktoberfest-accepted

#153 Create WorldClock.py
  Programs/WorldClock.py
Labels: hacktoberfest-accepted

#152 Create Queue_to_stack.c
  Program/Queue_to_stack.c
Labels: hacktoberfest-accepted

#136 Create No_of_Bst's.java
  programs/No_of_Bst's.java
Labels: hacktoberfest-accepted

#149 Create rainbowA.cpp
  Programs/rainbowA.cpp
Labels: hacktoberfest-accepted

#117 Create Two_tops_in_common_stack.c
  Programs/Two_tops_in_common_stack.c
Labels: hacktoberfest-accepted

#33 Create Repeated_String.cpp
  Programs/Repeated_String.cpp
Labels: hacktoberfest-accepted

#36 Create Sales_by_match.cpp
  Programs/Sales_by_match.cpp
Labels: hacktoberfest-accepted

#37 Create GCD_OPS.cpp
  Programs/GCD_OPS.cpp
Labels: hacktoberfest-accepted

#120 Create Double_ended_queue.c
  Programs/Double_ended_queue.c
Labels: hacktoberfest-accepted

#157 Create stack.cpp
  Programs/stack.cpp
Labels: hacktoberfest-accepted

#164 Create Search_in_sorted_rotated_array.cpp
  Programs/Search_in_sorted_rotated_array.cpp
Labels: hacktoberfest-accepted

#100 Create Change from celsius to fahrenheit.java
  Programs/Change from celsius to fahrenheit.java
Labels: hacktoberfest-accepted

#182 Pascal's Triangle
  Programs/Pascal's Triangle
Labels: hacktoberfest-accepted

#184 Caesar Cipher.cpp
  Programs/Caesar Cipher.cpp
Labels: hacktoberfest-accepted

#180 Brackets-LongestSubstring.py
  Programs/Brackets-LongestSubstring.py
Labels: hacktoberfest-accepted

#179 InterpretCode.py
  Interpret Code
  Programs/InterpretCode.py
Labels: hacktoberfest-accepted

#178 RockPaperScissors in C
  Programs/RockPaperScissors.c
  Programs/TicTacToe.c
  Programs/binary_tree.c
Labels: hacktoberfest-accepted

#177 Added code for Automorphic Number in Java..
  AutomorphicNumber.java
Labels: hacktoberfest-accepted

#186 Null Cipher.py
  Programs/Null Cipher.py
Labels: hacktoberfest-accepted

#188 Sorting Using sort().java
  Programs/Sorting Using sort().java
Labels: hacktoberfest-accepted

#202 Create ExecutionTimeMergeSort.c
  Programs/ExecutionTimeMergeSort.c
  Programs/ExecutionTimeQuickSort.c
Labels: hacktoberfest-accepted

#201 Create palindrome(iterative).cpp
  Programs/palindrome(iterative).cpp
  Programs/ternarysearch.cpp
Labels: hacktoberfest-accepted

#206 Create ExecutionTimeSelectionSort.c
  Programs/ExecutionTimeSelectionSort.c
Labels: hacktoberfest-accepted

#205 Create numbergame.cpp
  Programs/numbergame.cpp
  circularlinkedlist.cpp
Labels: hacktoberfest-accepted

#200 Create PlusOne.cpp
  Programs/PlusOne.cpp
Labels: hacktoberfest-accepted

#204 Add Adjacency List and matrix and sort programs.
  Programs/graph-adjacencylist.py
  Programs/graph-adjacencymatrix.py
  Programs/mergesort.py
  Programs/quicksort.py
  Programs/selectionsort.py
Labels: good first issue, hacktoberfest-accepted

#203 added code
  Programs/hadamard_matrix.java
Labels: hacktoberfest-accepted

#199 Create armstrong.cpp
  Programs/armstrong.cpp
Labels: hacktoberfest-accepted

#197 Create FindingExcelCol_NO.cpp
  Programs/FindingExcelCol_NO.cpp
Labels: hacktoberfest-accepted

#195 Create solveSudoku.cpp
  Programs/ratinMaze.cpp
  Programs/solveSudoku.cpp
Labels: hacktoberfest-accepted

#189 Create multiplayer-tic-tac-toe-game-in-python.py
  Programs/multiplayer-tic-tac-toe-game-in-python.py
Labels: hacktoberfest-accepted

#172 Create leap year.cpp
  Programs/leap year.cpp
Labels: hacktoberfest-accepted

#171 Next palindrome prime.c
  Programs/Next palindrome prime.c
Labels: hacktoberfest-accepted

#170 Create jumpsearch.java
  Programs/jumpsearch.java
Labels: hacktoberfest-accepted

#115 Create WrapperClass.java
  Programs/StaticBinding.java
  Programs/WrapperClass.java
Labels: hacktoberfest-accepted

#213 BubbleSort.cpp
  Programs/BubbleSort.cpp
  Programs/SelectionSort.cpp
Labels: hacktoberfest-accepted

#207 A program to find the size of a image using python
  Programs/Find-size-of-a-image.py
Labels: hacktoberfest-accepted

#214 Tower of Hanoi.py
  Programs/Tower of Hanoi.py
Labels: hacktoberfest-accepted

#211 Create gcd.cpp
  Programs/gcd.cpp
Labels: hacktoberfest-accepted

#210 Create array_mis.cpp
  Programs/array_mis.cpp
Labels: hacktoberfest-accepted

#209 Create string_reverse_stl.cpp
  Programs/string_reverse_stl.cpp
Labels: hacktoberfest-accepted

#215 Create Kth Smallest Element.cpp
  Programs/Kth Smallest Element.cpp
Labels: hacktoberfest-accepted

#217 LinearSearch.cpp
  Programs/LinearSearch.cpp
Labels: hacktoberfest-accepted

#219 Create ExecutionTimeBubbleSort.c
  Programs/ExecutionTimeBubbleSort.c
Labels: hacktoberfest-accepted

#216 Selection_Sort.cpp
  Programs/Selection_Sort.cpp
Labels: hacktoberfest-accepted

#223 Create election.sol
  Programs/election.sol
Labels: hacktoberfest-accepted

#225 Substitution Cipher
  Programs/Substitution Cipher.cpp
Labels: hacktoberfest-accepted

#231 Added Palindrom Algo In Go Lang
  Programs/Program_In_Go/Palindrom.go
Labels: hacktoberfest-accepted

#244 Create tic_tac_toe.py
  Programs/tic_tac_toe.py
Labels: hacktoberfest-accepted

#241 Create face_swap.py
  Programs/face_swap.py
Labels: hacktoberfest-accepted

#242 Create atm_management.py
  Programs/atm_management.py
Labels: hacktoberfest-accepted

#192 Topological_Sort.cpp
  Programs/Topological_Sort.cpp
Labels: hacktoberfest-accepted

#193 Longest_Common_Subsequence.cpp
  Programs/Longest_Common_Subsequence.cpp
Labels: hacktoberfest-accepted

#194 Heap_Sort.cpp
  Programs/Heap_Sort.cpp
Labels: hacktoberfest-accepted

#212 ProductOfArrayExceptitself
  Programs/ProductOfArrayExceptItself.cpp
Labels: hacktoberfest-accepted

#222 Create CovidRun(Codechef Long Challenge Oct 2020)
  Programs/CovidRun.cpp
Labels: hacktoberfest-accepted

#247 Create Word_Ladder.cpp
  Programs/Word_Ladder.cpp
Labels: hacktoberfest-accepted

#254 Create Rat in a maze.java
  Programs/Rat in a maze.java
Labels: hacktoberfest-accepted

#255 Create nth fibonacci with memoization.C
  Programs/nth fibonacci with memoization.C
Labels: hacktoberfest-accepted

#257 Create Minimum gifts.cpp
  Programs/Minimum gifts.cpp
Labels: hacktoberfest-accepted

#238 Create Third smallest number in an unsorted array
  Programs/Third smallest number in an unsorted array.C
Labels: hacktoberfest-accepted

#248 Added Binary Search Algo In Go Lang
  Programs/Program_In_Go/ArmstrongNumber.go
  Programs/Program_In_Go/Binary_Search.go
Labels: hacktoberfest-accepted

#259 Create n-queen.py
  Programs/n-queen.py
Labels: hacktoberfest-accepted

#263 Create passwordGEN.py
  Programs/passwordGEN.py
Labels: hacktoberfest-accepted

#273 printpostorder
  Programs/postorder.cpp
Labels: hacktoberfest-accepted

#253 Create Reverse LinkedList.cpp
  Programs/Cycle Detection in LinkedList.cpp
  Programs/Reverse LinkedList.cpp
Labels: hacktoberfest-accepted

#266 Create Fibonacci with memoization in Java
  Programs/Fibonacci.java
Labels: hacktoberfest-accepted

#267 Create Circular_Queue.c
  Programs/Circular_Queue.c
Labels: hacktoberfest-accepted

#268 adding vowel and constant related problem
  Programs/vowel-consonant.c
Labels: hacktoberfest-accepted

#269 Added K-NearestNeighbour (K-NN) Classifier Algorithm
  Programs/Machine_Learning_Algo/KNNClassifier.py
Labels: hacktoberfest-accepted

#271 Create fact_recursion.cpp
  Programs/fact_recursion.cpp
Labels: hacktoberfest-accepted

#272 Create n_to_1_recursion.cpp
  n_to_1_recursion.cpp
Labels: hacktoberfest-accepted

#275 Create Max pairwise prod.cpp
  Programs/Max pairwise prod.cpp
Labels: hacktoberfest-accepted

#274 Create Three largest 9 digit palindrome prime.C
  Programs/Three largest 9 digit palindrome prime.C
Labels: hacktoberfest-accepted

#191 LexicoGraphic_Rank_of_String.cpp
  Programs/Lexicographic_Rank.cpp
Labels: hacktoberfest-accepted

#276 Create Searching in sorted 2D Array
  Programs/Searching in sorted 2D Array.java
Labels: hacktoberfest-accepted

#277 Create Antisudoku.cpp
  Programs/Antisudoku.cpp
Labels: hacktoberfest-accepted

#278 sort by frequency
  Programs/sort by freq.cpp
Labels: hacktoberfest-accepted

#279 Create fibonacci.go
  Programs/Program_In_Go/fibonacci.go
Labels: hacktoberfest-accepted

#281 Kadane's Algorithm
  Programs/Kadane's Algorithm.cpp
Labels: hacktoberfest-accepted

#283 Create spiral.py
  Programs/spiral.py
Labels: hacktoberfest-accepted

#286 Create input_Password.py
  Programs/input_Password.py
Labels: hacktoberfest-accepted

#282 Create factorial.cpp
  Programs/factorial.cpp
Labels: hacktoberfest-accepted

#264 Create convertByteUnits.js
  convertByteUnits.js
  hello_world.rb
Labels: invalid

#280 Added a simple program for 2D matrix multiplication in C++
  Programs/matrix_multiplication.cpp
Labels: hacktoberfest-accepted

#293 converting infix to postfix expression
  Programs/infix-postfix.c
Labels: hacktoberfest-accepted

#298 Added Program For String Manipulation
  Programs/StringManipulation.cpp
Labels: hacktoberfest-accepted

#309 Alert & Popup Window Handling in Selenium WebDriver
  Programs/AlertDemo.java
  Programs/firsttestngfile.java
Labels: hacktoberfest-accepted

#307 Create Dijkstra.py
  Programs/Dijkstra.py
Labels: hacktoberfest-accepted

#312 Added Neural Network Algo with Backpropagation
  Programs/Machine_Learning_Algo/Neural_Network.py
Labels: hacktoberfest-accepted

#287 Program To print intersection of two sorted arrays
  Programs/IntersectionOfSortedArrays.cpp
Labels: hacktoberfest-accepted

#319 Create sieve of eratosthenes.cpp
  Programs/sieve of eratosthenes.cpp
Labels: hacktoberfest-accepted

#320 Create Binary search in a sorted 2d array.cpp
  Programs/Binary search in a sorted 2d array.cpp
Labels: hacktoberfest-accepted

#321 Create maximum coin change problem(DP).cpp
  Programs/maximum coin change problem(DP).cpp
Labels: hacktoberfest-accepted

#322 simpleForm
  Programs/simpleForm.html
Labels: hacktoberfest-accepted

#326 Hackerrank LeetCode DS problem solutions
  Programs/Hackerrank-Leetcode-Solutions/ArrayManipulation-Hackerrank-bruteforce.cpp
  Programs/Hackerrank-Leetcode-Solutions/ArrayManipulation-Hackerrank-diffCompare.cpp
  Programs/Hackerrank-Leetcode-Solutions/ContainsDuplicateII-LeetCode.cpp
  Programs/Hackerrank-Leetcode-Solutions/CovidRun-CodeChef.cpp
  Programs/Hackerrank-Leetcode-Solutions/DynamicArray-Hackerrank.cpp
  Programs/Hackerrank-Leetcode-Solutions/LeftRotation-Hackerrank.cpp
  Programs/Hackerrank-Leetcode-Solutions/README.md
  Programs/Hackerrank-Leetcode-Solutions/SparseArrays-Hackerrank.cpp
  Programs/Hackerrank-Leetcode-Solutions/TwoSum-LeetCode.cpp
  Programs/Hackerrank-Leetcode-Solutions/VariableSizedArray-Hackerrank.cpp
  Programs/Hackerrank-Leetcode-Solutions/duplicates-LeetCode.cpp
  Programs/Hackerrank-Leetcode-Solutions/maxSum-LeetCode.cpp
  Programs/Hackerrank-Leetcode-Solutions/moveZeros-LeetCode.cpp
  Programs/Hackerrank-Leetcode-Solutions/rotate-LeetCode.cpp
Labels: hacktoberfest-accepted

#327 Bracket balancing using stack.c
  Programs/Expression_balancing.c
Labels: hacktoberfest-accepted

#328 Create Partition_linked_list.cpp
  Programs/Partition_linked_list.cpp
Labels: hacktoberfest-accepted

#329 Create AVL with duplicate keys.cpp
  Programs/AVL with duplicate keys.cpp
Labels: hacktoberfest-accepted

#330 Create Warnsdorff’s algorithm for Knight’s tour problem.cpp
  Programs/Warnsdorff’s algorithm for Knight’s tour problem.cpp
Labels: hacktoberfest-accepted

#331 Create Construct a Binary Tree from postorder and Inorder.cpp
  Programs/Construct a Binary Tree from Postorder and Inorder.cpp
Labels: hacktoberfest-accepted
